# Generated by Django 5.2.17 on 2026-08-17 06:57

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Overrides seo_title on social cards. Leave blank to reuse seo_title.', max_length=255, verbose_name='OpenGraph title')),
                ('og_description', models.TextField(blank=True, help_text='Overrides search_description on social cards.', verbose_name='OpenGraph description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL for pages syndicated from elsewhere.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro rendered above main content and used as fallback description.')),
                ('intro', wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {})})),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Social sharing image')),
            ],
            options={
                'verbose_name': 'Blog index',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Overrides page link if set.', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('open_in_new_tab', 3)]], {})})),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer menu',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Overrides seo_title on social cards. Leave blank to reuse seo_title.', max_length=255, verbose_name='OpenGraph title')),
                ('og_description', models.TextField(blank=True, help_text='Overrides search_description on social cards.', verbose_name='OpenGraph description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL for pages syndicated from elsewhere.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro rendered above main content and used as fallback description.')),
                ('hero', wagtail.fields.StreamField([('hero', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('image', 2), ('cta_label', 3), ('cta_url', 4), ('align', 5)]], {})})),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 5)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {})})),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Social sharing image')),
            ],
            options={
                'verbose_name': 'Home page',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Overrides page link if set.', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('open_in_new_tab', 3)]], {})})),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Main menu',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, help_text='Short tagline shown in the header and used in default OG descriptions.', max_length=200)),
                ('footer_text', models.TextField(blank=True, help_text='Copyright / colophon shown in the footer.')),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Overrides seo_title on social cards. Leave blank to reuse seo_title.', max_length=255, verbose_name='OpenGraph title')),
                ('og_description', models.TextField(blank=True, help_text='Overrides search_description on social cards.', verbose_name='OpenGraph description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL for pages syndicated from elsewhere.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro rendered above main content and used as fallback description.')),
                ('date', models.DateField(verbose_name='Post date')),
                ('hero', wagtail.fields.StreamField([('hero', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('image', 2), ('cta_label', 3), ('cta_url', 4), ('align', 5)]], {})})),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 5), ('columns', 8)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two'), ('3', 'Three'), ('4', 'Four')]}), 7: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('quote', 5)]], {'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('columns', 6), ('items', 7)]], {})})),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='models.author')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Social sharing image')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='models.tag')),
            ],
            options={
                'verbose_name': 'Blog post',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
