# Generated by Django 5.2.17 on 2026-08-19 09:07

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_heading',
            field=models.CharField(blank=True, default='About Me', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='availability_label',
            field=models.CharField(blank=True, help_text="Small tag above the hero heading (e.g. 'AVAILABLE FOR NEW PROJECTS').", max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_heading',
            field=models.CharField(blank=True, default='Recent Blog Posts', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many recent blog posts to feature.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_code',
            field=models.TextField(blank=True, help_text='Optional code snippet displayed in the terminal card next to the hero.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_heading',
            field=models.CharField(blank=True, default='Featured Projects', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 5), ('columns', 8)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {}), 1: ('models.api.images.APIImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two'), ('3', 'Three'), ('4', 'Four')]}), 7: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('quote', 5)]], {'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('columns', 6), ('items', 7)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('models.api.images.APIImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('image', 2), ('cta_label', 3), ('cta_url', 4), ('align', 5)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 5)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {}), 1: ('models.api.images.APIImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {})}),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short summary shown on project cards.')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Tech pills shown on the card. Example: ["Go", "gRPC", "Raft"]')),
                ('project_url', models.URLField(blank=True, help_text="External or internal URL for the 'View Project' link.")),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HomePageFeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_project_entries', to='models.homepage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='models.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
