# Generated by Django 5.2.17 on 2026-08-19 09:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_homepage_hero_homepage_about_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 5), ('callout', 8), ('columns', 11)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {}), 1: ('models.api.images.APIImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Key Takeaway', 'help_text': 'Bold label at the top of the callout.', 'max_length': 60, 'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('success', 'Success (green)'), ('info', 'Info (blue)'), ('warning', 'Warning (amber)')]}), 8: ('wagtail.blocks.StructBlock', [[('label', 6), ('body', 4), ('variant', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two'), ('3', 'Three'), ('4', 'Four')]}), 10: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('quote', 5)]], {'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('columns', 9), ('items', 10)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 5), ('callout', 8)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {}), 1: ('models.api.images.APIImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Key Takeaway', 'help_text': 'Bold label at the top of the callout.', 'max_length': 60, 'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('success', 'Success (green)'), ('info', 'Info (blue)'), ('warning', 'Warning (amber)')]}), 8: ('wagtail.blocks.StructBlock', [[('label', 6), ('body', 4), ('variant', 7)]], {})}),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category (shown as the emerald label above the title).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='models.category'),
        ),
    ]
