# Generated by Django 5.2.17 on 2026-08-19 10:07

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_category_alter_blogpage_body_alter_homepage_body_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Overrides seo_title on social cards. Leave blank to reuse seo_title.', max_length=255, verbose_name='OpenGraph title')),
                ('og_description', models.TextField(blank=True, help_text='Overrides search_description on social cards.', verbose_name='OpenGraph description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL for pages syndicated from elsewhere.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro rendered above main content and used as fallback description.')),
                ('intro', wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('models.streamfield.blocks.RichTextBlock', (), {})})),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Social sharing image')),
            ],
            options={
                'verbose_name': 'Project index',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Overrides seo_title on social cards. Leave blank to reuse seo_title.', max_length=255, verbose_name='OpenGraph title')),
                ('og_description', models.TextField(blank=True, help_text='Overrides search_description on social cards.', verbose_name='OpenGraph description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL for pages syndicated from elsewhere.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro rendered above main content and used as fallback description.')),
                ('role', models.CharField(blank=True, help_text="Your role on this project, e.g. 'Sole Creator' or 'Lead Engineer'.", max_length=120)),
                ('completed_label', models.CharField(blank=True, help_text="Free-form completion label, e.g. 'Q3 2024' or 'In progress'.", max_length=60)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Tech pills shown under the title. Example: ["Go", "gRPC", "Raft"]')),
                ('project_url', models.URLField(blank=True, help_text="Live site URL (renders the 'View Live Site' CTA).")),
                ('source_url', models.URLField(blank=True, help_text="Repository URL (renders the 'View Source Code' CTA).")),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Social sharing image')),
            ],
            options={
                'verbose_name': 'Project',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AlterField(
            model_name='homepagefeaturedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='models.projectpage'),
        ),
        migrations.CreateModel(
            name='ProjectPageKeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='models.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPageTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='models.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
