# Generated by Django 5.2.17 on 2026-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_projectindexpage_projectpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text="Maximum number of featured projects shown on the homepage. Populated from Project pages with 'Featured' turned on, in tree order."),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='featured',
            field=models.BooleanField(default=False, help_text="Show this project in the 'Featured Projects' strip on the homepage."),
        ),
        migrations.DeleteModel(
            name='HomePageFeaturedProject',
        ),
    ]
