# Generated by Django 5.2.17 on 2026-08-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_homepage_featured_limit_projectpage_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='hero',
        ),
    ]
