# Generated by Django 5.2.17 on 2026-08-19 10:33
#
# Autogenerated ``AlterField`` on ``BlogPage.tags`` had to be split into
# ``RemoveField`` + ``AddField`` because Django can't alter an M2M's
# ``through=`` directly (see :class:`ValueError` "you cannot alter to or from
# M2M fields, or add or remove through= on M2M fields"). Any existing
# ``BlogPage``\ -to-old-``Tag`` links are dropped -- taggit tags will be added
# fresh via the new admin input.

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_remove_blogpage_hero'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='models.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='models.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
