# Generated by Django 5.2.17 on 2026-08-20 20:49

import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_blogpagetag_delete_tag_alter_blogpage_tags'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=280)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Overrides seo_title on social cards. Leave blank to reuse seo_title.', max_length=255, verbose_name='OpenGraph title')),
                ('og_description', models.TextField(blank=True, help_text='Overrides search_description on social cards.', verbose_name='OpenGraph description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical URL for pages syndicated from elsewhere.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro rendered above main content and used as fallback description.')),
                ('contact_email', models.EmailField(blank=True, help_text='Public email address shown in the sidebar (used for the mailto: link).', max_length=254)),
                ('response_time_note', models.CharField(blank=True, default='I typically respond within 24 business hours.', help_text='Short note shown below the contact email.', max_length=280)),
                ('terminal_filename', models.CharField(blank=True, default='contact.sh', help_text='Title displayed in the terminal window chrome.', max_length=60)),
                ('hermes_greeting', wagtail.fields.RichTextField(blank=True, help_text="First line printed by the assistant when the visitor types 'chat' in the terminal. Leave blank to skip a greeting.")),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Social sharing image')),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
