# Development inventory - runs against the host you're calling ansible from.
all:
  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
